Document: canaima-primeros-pasos
Title: Debian canaima-primeros-pasos Manual
Author: <insert document author here>
Abstract: This manual describes what canaima-primeros-pasos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/canaima-primeros-pasos/canaima-primeros-pasos.sgml.gz

Format: postscript
Files: /usr/share/doc/canaima-primeros-pasos/canaima-primeros-pasos.ps.gz

Format: text
Files: /usr/share/doc/canaima-primeros-pasos/canaima-primeros-pasos.text.gz

Format: HTML
Index: /usr/share/doc/canaima-primeros-pasos/html/index.html
Files: /usr/share/doc/canaima-primeros-pasos/html/*.html
